#!/usr/bin/env python3

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Convert Palace farfield CSV data to VTK format for visualization.

Usage:
    python3 farfield_csv2pvd.py farfield-E-*.csv

    or

    pvpython farfield_csv2pvd.py farfield-E-*.csv

Input CSV files are generated by Palace farfield postprocessing. Creates VTU
files in farfield_vtk/ subfolder and a PVD file that contains all the
frequencies. To visualize, open `farfield.pvd` with ParaView.

Automatically detects full sphere data (theta: 0-180°, phi: 0-360°) and creates
surface connectivity. For partial sphere data, creates a point cloud.

Requires numpy and vtk.

"""

import numpy as np
import sys

try:
    import vtk
except ImportError:
    print("Error: VTK library not found. Please install it with:")
    print("  pip install vtk")
    print("Alternatively, use pvpython.")
    sys.exit(1)

import re
import os


def add_vector_field(
    grid: vtk.vtkUnstructuredGrid,
    data: np.ndarray,
    name: str,
    components: tuple[int, int, int],
) -> None:
    """Add a 3-component vector field to the grid."""
    array = vtk.vtkDoubleArray()
    array.SetName(name)
    array.SetNumberOfComponents(3)
    array.SetNumberOfTuples(len(data))

    for i in range(len(data)):
        array.SetTuple3(
            i, data[i, components[0]], data[i, components[1]], data[i, components[2]]
        )

    grid.GetPointData().AddArray(array)


def add_scalar_field(
    grid: vtk.vtkUnstructuredGrid, data: np.ndarray, name: str
) -> None:
    """Add a scalar field to the grid."""
    array = vtk.vtkDoubleArray()
    array.SetName(name)
    array.SetNumberOfTuples(len(data))
    for i in range(len(data)):
        array.SetValue(i, data[i])
    grid.GetPointData().AddArray(array)


def create_connectivity(
    grid: vtk.vtkUnstructuredGrid,
    extended_data: np.ndarray,
    point_map: dict[tuple[float, float], int],
) -> None:
    """Create mesh connectivity for full sphere or point cloud for partial data.

    We identify if we are working with a full sphere checking that the data
    covers the poles and that the azimuthal direction covers the range 0 to 360.
    """
    theta_unique = np.unique(extended_data[:, 0])

    # Check if data spans full sphere.
    has_poles = 0.0 in theta_unique and 180.0 in theta_unique
    phi_range = np.max(extended_data[:, 1]) - np.min(extended_data[:, 1])
    spans_full_sphere = has_poles and phi_range >= 360.0

    if spans_full_sphere:
        # Create spherical mesh connectivity by processing adjacent theta rings:
        # 1. For each pair of consecutive theta levels (θᵢ, θᵢ₊₁)
        # 2. Get available phi values at both theta levels
        # 3. Connect points based on location:
        #    - North pole (θ≈0): fan triangles from single pole point to next ring
        #    - South pole (θ≈180): fan triangles from previous ring to single pole point
        #    - Regular regions: rectangles matching phi points on both rings

        for i in range(len(theta_unique) - 1):
            theta_curr, theta_next = theta_unique[i], theta_unique[i + 1]
            phi_curr = sorted([p for (t, p) in point_map.keys() if t == theta_curr])
            phi_next = sorted([p for (t, p) in point_map.keys() if t == theta_next])

            if abs(theta_curr) < 1e-8:  # North pole triangles
                for j in range(len(phi_next) - 1):
                    tri = vtk.vtkTriangle()
                    tri.GetPointIds().SetId(0, point_map[(0.0, 0.0)])
                    tri.GetPointIds().SetId(1, point_map[(theta_next, phi_next[j])])
                    tri.GetPointIds().SetId(2, point_map[(theta_next, phi_next[j + 1])])
                    grid.InsertNextCell(tri.GetCellType(), tri.GetPointIds())
            elif abs(theta_next - 180) < 1e-8:  # South pole triangles
                for j in range(len(phi_curr) - 1):
                    tri = vtk.vtkTriangle()
                    tri.GetPointIds().SetId(0, point_map[(theta_curr, phi_curr[j])])
                    tri.GetPointIds().SetId(1, point_map[(theta_curr, phi_curr[j + 1])])
                    tri.GetPointIds().SetId(2, point_map[(180.0, 0.0)])
                    grid.InsertNextCell(tri.GetCellType(), tri.GetPointIds())
            else:  # Regular quads
                common_phi = sorted(set(phi_curr) & set(phi_next))
                for j in range(len(common_phi) - 1):
                    phi1, phi2 = common_phi[j], common_phi[j + 1]
                    quad = vtk.vtkQuad()
                    quad.GetPointIds().SetId(0, point_map[(theta_curr, phi1)])
                    quad.GetPointIds().SetId(1, point_map[(theta_curr, phi2)])
                    quad.GetPointIds().SetId(2, point_map[(theta_next, phi2)])
                    quad.GetPointIds().SetId(3, point_map[(theta_next, phi1)])
                    grid.InsertNextCell(quad.GetCellType(), quad.GetPointIds())
    else:
        # If we don't have a full sphere, we don't bother with trying to
        # reconstruct connectivity. Instead, we add add vertex cells for point
        # cloud visualization.
        for i in range(len(extended_data)):
            vertex = vtk.vtkVertex()
            vertex.GetPointIds().SetId(0, i)
            grid.InsertNextCell(vertex.GetCellType(), vertex.GetPointIds())


def process_csv_file(filename: str) -> vtk.vtkUnstructuredGrid:
    """Read a farfield CSV file and return an unstructured grid.

    The resulting grid is defined on the unit sphere and has a mix of
    quadrangular and triangular connectivity (for the poles).
    """

    # Read and extend data with periodic boundary.
    data = np.loadtxt(filename, delimiter=",", skiprows=1)
    # Duplicate the data at phi = 0. This helps with closing the connectivity.
    # (phi = 0 is the same same phi = 360.)
    phi_0_data = data[data[:, 1] == 0.0].copy()
    phi_0_data[:, 1] = 360.0
    extended_data = np.vstack([data, phi_0_data])

    # Convert to Cartesian coordinates on the unit sphere.
    theta_rad = np.deg2rad(extended_data[:, 0])
    phi_rad = np.deg2rad(extended_data[:, 1])
    x = np.sin(theta_rad) * np.cos(phi_rad)
    y = np.sin(theta_rad) * np.sin(phi_rad)
    z = np.cos(theta_rad)

    # Create VTK grid and points.
    grid = vtk.vtkUnstructuredGrid()
    points = vtk.vtkPoints()
    for i in range(len(x)):
        points.InsertNextPoint(x[i], y[i], z[i])
    grid.SetPoints(points)

    # Build point mapping and create connectivity.
    point_map: dict[tuple[float, float], int] = {
        (t, p): i
        for i, (t, p) in enumerate(zip(extended_data[:, 0], extended_data[:, 1]))
    }
    create_connectivity(grid, extended_data, point_map)

    # Add field data (using alternate columns to separate real and imaginary
    # components).
    add_vector_field(grid, extended_data, "E_real", (2, 4, 6))
    add_vector_field(grid, extended_data, "E_imag", (3, 5, 7))

    # Add magnitude.
    E_mag = np.sqrt(np.sum(extended_data[:, 2:8] ** 2, axis=1))
    add_scalar_field(grid, E_mag, "E_magnitude")

    return grid


def main() -> None:
    if len(sys.argv) < 2:
        print(
            "Usage: python3 farfield_csv2pvd.py <farfield_csv_file> [additional_files...]"
        )
        sys.exit(1)

    # Create output directory
    os.makedirs("farfield_vtk", exist_ok=True)

    # Process files and extract frequencies
    freq_pattern = re.compile(r"farfield-E-([+-]?\d+\.\d+e[+-]?\d+)\.csv")
    files_data: list[tuple[float, str]] = []

    for filename in sys.argv[1:]:
        match_ = freq_pattern.search(filename)
        if match_:
            frequency = float(match_.group(1))
            grid = process_csv_file(filename)

            # Write VTU file.
            vtu_filename = f"farfield_vtk/farfield_{frequency:.8e}.vtu"
            writer = vtk.vtkXMLUnstructuredGridWriter()
            writer.SetFileName(vtu_filename)
            writer.SetInputData(grid)
            writer.Write()

            files_data.append((frequency, os.path.basename(vtu_filename)))
            print(f"Processed {filename} -> {vtu_filename}")

    # Sort by frequency and create PVD file.
    files_data.sort(key=lambda x: x[0])

    with open("farfield.pvd", "w") as pvd:
        pvd.write('<?xml version="1.0"?>\n')
        pvd.write(
            '<VTKFile type="Collection" version="2.2" byte_order="LittleEndian">\n'
        )
        pvd.write("  <Collection>\n")

        for freq, vtu_file in files_data:
            pvd.write(
                f'    <DataSet timestep="{freq}" file="farfield_vtk/{vtu_file}"/>\n'
            )

        pvd.write("  </Collection>\n")
        pvd.write("</VTKFile>\n")

    print(f"Created farfield.pvd with {len(files_data)} frequencies")


if __name__ == "__main__":
    main()
