# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Re-mesh the region of a substructuring mesh for a new design (see the substructuring
documentation).

An offline substructuring run condenses the environment of a split mesh (region + environment)
into a saved model. To evaluate a new design of the region online, the new mesh must keep the
environment and the region/environment interface exactly as they were. This script builds
such a mesh from

  --model   the split mesh used for the offline run (environment and interface are kept), and
  --design  a full mesh of the new design, e.g. regenerated by the layout tool with changed
            parameters, with the same attribute conventions.

The region is assumed to contain two materials separated by a layout plane z = --plane-z
(e.g. substrate below and vacuum above) and planar features on that plane (metal and other
boundary attributes). The layout inside the region is taken from the design mesh; the region
is re-tetrahedralized with Gmsh against the fixed interface, with element sizes following the
design mesh. The script checks that the design matches the model outside the region and at
the interface.

Usage:

    python3 remesh_region.py --model MODEL.msh2 --design DESIGN.msh2 --output OUT.msh2
        [--region-attributes BELOW ABOVE] [--plane-z Z]

Requires the gmsh and numpy Python packages (pip install gmsh numpy).
"""

import argparse
import collections
import math
import struct
import sys

import gmsh
import numpy as np

# Nodes per Gmsh element type (the types that can appear in these meshes).
NODES_PER_ELEMENT = {1: 2, 2: 3, 4: 4, 8: 3, 9: 6, 11: 10, 15: 1}
TRIANGLES, TETRAHEDRA = (2, 9), (4, 11)
TET_FACES = ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))
TET_EDGES = ((0, 1), (1, 2), (0, 2), (0, 3), (2, 3), (1, 3))  # 10-node mid nodes 4..9
TRI_EDGES = ((0, 1), (1, 2), (0, 2))  # 6-node mid nodes 3..5


def read_msh2(path):
    """Read a Gmsh 2.2 mesh (ASCII or binary) into (physical names, nodes, elements)."""
    data = open(path, "rb").read()
    pos = 0

    def line():
        nonlocal pos
        end = data.index(b"\n", pos)
        text = data[pos:end].decode()
        pos = end + 1
        return text

    names, nodes, elements, binary = [], {}, [], False
    while pos < len(data):
        section = line().strip()
        if section == "$MeshFormat":
            binary = int(line().split()[1]) == 1
            if binary:
                pos += 4  # endianness check integer
                line()
            line()
        elif section == "$PhysicalNames":
            names = [line() for _ in range(int(line()))]
            line()
        elif section == "$Nodes":
            for _ in range(int(line())):
                if binary:
                    i, x, y, z = struct.unpack_from("<iddd", data, pos)
                    pos += 28
                else:
                    f = line().split()
                    i, x, y, z = int(f[0]), float(f[1]), float(f[2]), float(f[3])
                nodes[i] = (x, y, z)
            if binary:
                line()
            line()
        elif section == "$Elements":
            count = int(line())
            if binary:
                while count > 0:
                    etype, num, ntags = struct.unpack_from("<iii", data, pos)
                    pos += 12
                    width = 1 + ntags + NODES_PER_ELEMENT[etype]
                    for _ in range(num):
                        rec = struct.unpack_from("<%di" % width, data, pos)
                        pos += 4 * width
                        elements.append((etype, list(rec[1 : 1 + ntags]), rec[1 + ntags :]))
                    count -= num
                line()
            else:
                for _ in range(count):
                    f = [int(v) for v in line().split()]
                    etype, ntags = f[1], f[2]
                    elements.append((etype, f[3 : 3 + ntags], tuple(f[3 + ntags :])))
            line()
        elif section:
            end = data.index(b"$End" + section[1:].encode(), pos)
            pos = data.index(b"\n", end) + 1
    return names, nodes, elements


def write_msh2(path, names, nodes, elements):
    """Write a binary Gmsh 2.2 mesh."""
    with open(path, "wb") as f:
        f.write(b"$MeshFormat\n2.2 1 8\n")
        f.write(struct.pack("<i", 1))
        f.write(b"\n$EndMeshFormat\n$PhysicalNames\n%d\n" % len(names))
        for name in names:
            f.write(name.encode() + b"\n")
        f.write(b"$EndPhysicalNames\n$Nodes\n%d\n" % len(nodes))
        for i, (x, y, z) in nodes.items():
            f.write(struct.pack("<iddd", i, x, y, z))
        f.write(b"\n$EndNodes\n$Elements\n%d\n" % len(elements))
        for num, (etype, tags, nd) in enumerate(elements, 1):
            f.write(struct.pack("<iii", etype, 1, len(tags)))
            f.write(struct.pack("<%di" % (1 + len(tags) + len(nd)), num, *tags, *nd))
        f.write(b"\n$EndElements\n")


class Layout:
    """The boundary triangles lying on the layout plane, with 2D point location."""

    def __init__(self, nodes, elements, plane_z):
        tri = [
            (tags[0], nd)
            for t, tags, nd in elements
            if t in TRIANGLES and all(abs(nodes[v][2] - plane_z) < 1e-9 for v in nd[:3])
        ]
        self.attr = np.array([a for a, _ in tri], dtype=int)
        self.conn = [nd for _, nd in tri]
        self.xy = np.array([[nodes[v][:2] for v in nd[:3]] for nd in self.conn])
        self.lo = self.xy.min(axis=(0, 1))
        self.cell = max((self.xy.max(axis=(0, 1)) - self.lo).max() / 400.0, 1e-12)
        self.grid = collections.defaultdict(list)
        tlo = np.floor((self.xy.min(axis=1) - self.lo) / self.cell).astype(int)
        thi = np.floor((self.xy.max(axis=1) - self.lo) / self.cell).astype(int)
        for t in range(len(tri)):
            for i in range(tlo[t, 0], thi[t, 0] + 1):
                for j in range(tlo[t, 1], thi[t, 1] + 1):
                    self.grid[(i, j)].append(t)

    def attribute_at(self, p):
        """Boundary attribute at the point p on the plane, or 0 if none (dielectric)."""
        i, j = np.floor((np.asarray(p) - self.lo) / self.cell).astype(int)
        for t in self.grid.get((i, j), ()):
            a, b, c = self.xy[t]
            d = (b[1] - c[1]) * (a[0] - c[0]) + (c[0] - b[0]) * (a[1] - c[1])
            l1 = ((b[1] - c[1]) * (p[0] - c[0]) + (c[0] - b[0]) * (p[1] - c[1])) / d
            l2 = ((c[1] - a[1]) * (p[0] - c[0]) + (a[0] - c[0]) * (p[1] - c[1])) / d
            if min(l1, l2, 1.0 - l1 - l2) >= -1e-12:
                return int(self.attr[t])
        return 0

    def feature_edges(self):
        """Edges separating different attributes (including attribute vs none), as
        (node a, node b, mid node or None)."""
        owners = collections.defaultdict(list)
        for t, nd in enumerate(self.conn):
            for k, (a, b) in enumerate(TRI_EDGES):
                mid = nd[3 + k] if len(nd) == 6 else None
                owners[tuple(sorted((nd[a], nd[b])))].append((self.attr[t], mid))
        return [
            (a, b, o[0][1])
            for (a, b), o in owners.items()
            if len(o) == 1 or o[0][0] != o[1][0]
        ]


class Face:
    """The region's part of the layout plane: a planar face bounded by fixed loops."""

    def __init__(self, nodes, faces):
        ecount = collections.Counter(
            tuple(sorted((f[p], f[q]))) for f in faces for p, q in TRI_EDGES
        )
        self.edges = {e for e, c in ecount.items() if c == 1}
        adj = collections.defaultdict(list)
        for a, b in self.edges:
            adj[a].append(b)
            adj[b].append(a)
        if any(len(v) != 2 for v in adj.values()):
            sys.exit("the region's layout-plane face has a pinched boundary (unsupported)")
        self.loops, seen = [], set()
        for start in adj:
            if start in seen:
                continue
            loop, prev = [start], None
            while True:
                seen.add(loop[-1])
                nxt = adj[loop[-1]][0] if adj[loop[-1]][0] != prev else adj[loop[-1]][1]
                if nxt == start:
                    break
                prev = loop[-1]
                loop.append(nxt)
            self.loops.append(loop)
        # Outer loop first (largest enclosed area), then holes.
        area = [
            abs(sum(nodes[l[i]][0] * nodes[l[i - 1]][1] - nodes[l[i - 1]][0] * nodes[l[i]][1]
                    for i in range(len(l))))
            for l in self.loops
        ]
        self.loops = [l for _, l in sorted(zip(area, self.loops), reverse=True)]
        self.polys = [np.array([nodes[v][:2] for v in l]) for l in self.loops]
        self.segments = [
            (p[i], p[(i + 1) % len(p)]) for p in self.polys for i in range(len(p))
        ]
        self.node_ids = [v for l in self.loops for v in l]
        self.node_xy = np.concatenate(self.polys)
        self.h = collections.defaultdict(float)  # longest adjacent boundary edge
        for a, b in self.edges:
            L = math.dist(nodes[a], nodes[b])
            self.h[a], self.h[b] = max(self.h[a], L), max(self.h[b], L)
        self.tol = 1e-6 * min(self.h.values())
        self.lo = self.node_xy.min(axis=0) - self.tol
        self.hi = self.node_xy.max(axis=0) + self.tol

    def contains(self, p):
        inside = False
        for poly in self.polys:
            x, y = poly[:, 0], poly[:, 1]
            x2, y2 = np.roll(x, -1), np.roll(y, -1)
            cross = (y > p[1]) != (y2 > p[1])
            with np.errstate(divide="ignore", invalid="ignore"):
                xi = (x2 - x) * (p[1] - y) / (y2 - y) + x
            inside ^= bool(np.count_nonzero(cross & (p[0] < xi)) % 2)
        return inside

    def snap(self, p):
        """Boundary node at p (within tolerance), or None."""
        d = np.linalg.norm(self.node_xy - np.asarray(p), axis=1)
        k = int(np.argmin(d))
        return self.node_ids[k] if d[k] <= self.tol else None

    def crosses(self, p, q):
        """Whether the open segment (p, q) properly intersects the boundary."""
        d = np.asarray(q) - np.asarray(p)
        for a, b in self.segments:
            e = b - a
            den = d[0] * e[1] - d[1] * e[0]
            if abs(den) < 1e-300:
                continue
            w = a - np.asarray(p)
            t = (w[0] * e[1] - w[1] * e[0]) / den
            u = (w[0] * d[1] - w[1] * d[0]) / den
            if 1e-9 < t < 1 - 1e-9 and 1e-9 < u < 1 - 1e-9:
                return True
        return False


def constraint_segments(face, nodes, layout, dnodes):
    """The design's feature edges inside the face, split at the face's boundary nodes they
    pass through; points on the boundary use the model's exact node coordinates."""
    segs = []
    for a, b, mid in layout.feature_edges():
        pts = [np.array(dnodes[a][:2]), np.array(dnodes[b][:2])]
        if mid is not None:  # follow curved edges through their mid node
            m = np.array(dnodes[mid][:2])
            if np.linalg.norm(m - 0.5 * (pts[0] + pts[1])) > 1e-6 * np.linalg.norm(
                pts[1] - pts[0]
            ):
                pts = [pts[0], m, pts[1]]
        for p, q in zip(pts[:-1], pts[1:]):
            if (np.maximum(p, q) < face.lo).any() or (np.minimum(p, q) > face.hi).any():
                continue
            d = q - p
            ts = [0.0, 1.0]
            for k, c in enumerate(face.node_xy):
                t = float((c - p) @ d) / float(d @ d)
                if 1e-9 < t < 1 - 1e-9 and np.linalg.norm(p + t * d - c) <= face.tol:
                    ts.append(t)
            ts.sort()
            for ta, tb in zip(ts[:-1], ts[1:]):
                u, v = p + ta * d, p + tb * d
                su, sv = face.snap(u), face.snap(v)
                u = tuple(nodes[su][:2]) if su is not None else tuple(u)
                v = tuple(nodes[sv][:2]) if sv is not None else tuple(v)
                if su is not None and sv is not None and tuple(sorted((su, sv))) in face.edges:
                    continue  # along the fixed boundary
                if face.crosses(u, v):
                    sys.exit(
                        "the design's layout crosses the region interface away from its "
                        "nodes near %s: the design differs from the model at the interface"
                        % (u,)
                    )
                if face.contains(((u[0] + v[0]) / 2, (u[1] + v[1]) / 2)):
                    segs.append((u, v))
    return segs


def check_environment(face, layout, model_layout):
    """Compare the layouts outside the region, in both directions."""
    mismatch, total = 0, 0
    for a, b in ((model_layout, layout), (layout, model_layout)):
        for t in range(len(a.attr)):
            c = a.xy[t].mean(axis=0)
            if not face.contains(c):
                total += 1
                mismatch += b.attribute_at(c) != a.attr[t]
    print("Environment layout check: %d of %d triangles differ" % (mismatch, total))
    if mismatch > 1e-3 * total:
        sys.exit("the design differs from the model outside the region")


def size_field(dnodes, delements, lo, hi):
    """Background mesh size from the design mesh: mean adjacent edge length at the nodes of
    its tetrahedra inside the box [lo, hi]."""
    tets = []
    for t, _, nd in delements:
        if t in TETRAHEDRA:
            c = np.mean([dnodes[v] for v in nd[:4]], axis=0)
            if (c >= lo).all() and (c <= hi).all():
                tets.append(nd[:4])
    hsum, hcnt = collections.Counter(), collections.Counter()
    for nd in tets:
        for p, q in TET_EDGES:
            L = math.dist(dnodes[nd[p]], dnodes[nd[q]])
            for v in (nd[p], nd[q]):
                hsum[v] += L
                hcnt[v] += 1
    data = []
    for nd in tets:
        xyz = [dnodes[v] for v in nd]
        data += [x[0] for x in xyz] + [x[1] for x in xyz] + [x[2] for x in xyz]
        data += [hsum[v] / hcnt[v] for v in nd]
    view = gmsh.view.add("design_size")
    gmsh.view.addListData(view, "SS", len(tets), data)
    field = gmsh.model.mesh.field.add("PostView")
    gmsh.model.mesh.field.setNumber(field, "ViewTag", view)
    gmsh.model.mesh.field.setAsBackgroundMesh(field)
    for opt in ("MeshSizeExtendFromBoundary", "MeshSizeFromPoints", "MeshSizeFromCurvature"):
        gmsh.option.setNumber("Mesh." + opt, 0)


def mesh_face(face, nodes, plane_z, segs, size):
    """Triangulate the face with Gmsh: fixed boundary edges, embedded feature edges."""
    gmsh.model.add("face")
    geo, tags = gmsh.model.geo, {}

    def point(xy):
        if xy not in tags:
            tags[xy] = geo.addPoint(xy[0], xy[1], plane_z)
        return tags[xy]

    loops, fixed = [], []
    for loop in face.loops:
        lines = [
            geo.addLine(point(tuple(nodes[a][:2])), point(tuple(nodes[b][:2])))
            for a, b in zip(loop, loop[1:] + loop[:1])
        ]
        fixed += lines
        loops.append(geo.addCurveLoop(lines))
    surf = geo.addPlaneSurface(loops)
    embedded = [geo.addLine(point(p), point(q)) for p, q in segs]
    geo.synchronize()
    for c in fixed:
        gmsh.model.mesh.setTransfiniteCurve(c, 2)  # keep the boundary edges as they are
    gmsh.model.mesh.embed(1, embedded, 2, surf)
    size()
    gmsh.model.mesh.generate(2)
    ids, xyz, _ = gmsh.model.mesh.getNodes()
    xyz = xyz.reshape(-1, 3)
    _, _, (tri,) = gmsh.model.mesh.getElements(2, surf)
    gmsh.model.remove()
    coord = {int(t): tuple(xyz[k]) for k, t in enumerate(ids)}
    return coord, tri.reshape(-1, 3).astype(int)


def mesh_volumes(boundary, coord, order, size):
    """Tetrahedralize the two region volumes bounded by the given triangles (boundary[1],
    boundary[2]: the fixed faces below and above the plane, boundary[3]: the plane face)."""
    gmsh.model.add("region")
    owner = {}
    for s in (3, 1, 2):
        gmsh.model.addDiscreteEntity(2, s)
        for f in boundary[s]:
            for v in f:
                owner.setdefault(v, s)
    for s in (1, 2, 3):
        vs = [v for v, o in owner.items() if o == s]
        gmsh.model.mesh.addNodes(2, s, vs, [x for v in vs for x in coord(v)])
    for s in (1, 2, 3):
        gmsh.model.mesh.addElementsByType(s, 2, [], [v for f in boundary[s] for v in f])
    for vol, shell in ((1, [1, 3]), (2, [2, 3])):
        gmsh.model.geo.addVolume([gmsh.model.geo.addSurfaceLoop(shell)], vol)
    gmsh.model.geo.synchronize()
    size()
    gmsh.option.setNumber("Mesh.Algorithm3D", 1)
    gmsh.model.mesh.generate(3)
    if order == 2:
        gmsh.model.mesh.setOrder(2)
    ids, xyz, _ = gmsh.model.mesh.getNodes()
    xyz = xyz.reshape(-1, 3)
    width = 10 if order == 2 else 4
    tets = {}
    for vol in (1, 2):
        _, _, (conn,) = gmsh.model.mesh.getElements(3, vol)
        tets[vol] = conn.reshape(-1, width).astype(int)
    _, _, (tri,) = gmsh.model.mesh.getElements(2, 3)
    gmsh.model.remove()
    gcoord = {int(t): tuple(float(x) for x in xyz[k]) for k, t in enumerate(ids)}
    return gcoord, tets, tri.reshape(-1, 6 if order == 2 else 3).astype(int), set(owner)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[1].strip())
    parser.add_argument("--model", required=True, help="split mesh of the offline run")
    parser.add_argument("--design", required=True, help="full mesh of the new design")
    parser.add_argument("--output", required=True, help="output mesh (Gmsh 2.2)")
    parser.add_argument(
        "--region-attributes",
        type=int,
        nargs=2,
        default=[1, 2],
        metavar=("BELOW", "ABOVE"),
        help="region element attributes below and above the layout plane",
    )
    parser.add_argument("--plane-z", type=float, default=0.0, help="layout plane z")
    args = parser.parse_args()
    below, above = args.region_attributes
    region = (below, above)

    # Model: region faces on the layout plane and fixed region boundary (the interface).
    names, nodes, elements = read_msh2(args.model)
    order = 2 if any(t == 11 for t, _, _ in elements) else 1
    attrs = collections.defaultdict(list)
    env_mid = {}
    for t, tags, nd in elements:
        if t in TETRAHEDRA:
            for f in TET_FACES:
                attrs[frozenset(nd[j] for j in f)].append(tags[0])
            if tags[0] not in region and len(nd) == 10:
                for k, (p, q) in enumerate(TET_EDGES):
                    env_mid[tuple(sorted((nd[p], nd[q])))] = nd[4 + k]
    plane, fixed = [], {1: [], 2: []}
    for key, a in attrs.items():
        r = [x for x in a if x in region]
        if not r or (len(r) == 2 and r[0] == r[1]):
            continue
        if len(r) == 2:
            plane.append(tuple(sorted(key)))
        else:
            fixed[1 if r[0] == below else 2].append(tuple(sorted(key)))
    if not plane:
        sys.exit("no region faces between attributes %d and %d" % (below, above))
    face = Face(nodes, plane)
    print(
        "Model: region face on the layout plane with %d triangles (%d boundary loops), "
        "%d interface triangles" % (len(plane), len(face.loops), len(fixed[1]) + len(fixed[2]))
    )

    # Design: layout inside the face, checked against the model elsewhere.
    _, dnodes, delements = read_msh2(args.design)
    layout = Layout(dnodes, delements, args.plane_z)
    check_environment(face, layout, Layout(nodes, elements, args.plane_z))
    segs = constraint_segments(face, nodes, layout, dnodes)
    box = np.array([nodes[v] for f in plane + fixed[1] + fixed[2] for v in f])
    pad = 0.1 * (box.max(axis=0) - box.min(axis=0))
    size = lambda: size_field(dnodes, delements, box.min(axis=0) - pad, box.max(axis=0) + pad)

    gmsh.initialize()
    gmsh.option.setNumber("General.Verbosity", 2)
    fcoord, ftri = mesh_face(face, nodes, args.plane_z, segs, size)

    # Output node ids: the model's for fixed boundary nodes, new ids for the rest.
    new_nodes, next_id = {}, max(nodes) + 1
    on_boundary = {tuple(nodes[v][:2]): v for v in face.node_ids}
    fmap = {}
    for t, xyz in fcoord.items():
        v = on_boundary.get(xyz[:2])
        if v is None:
            v, next_id = next_id, next_id + 1
            new_nodes[v] = (xyz[0], xyz[1], args.plane_z)
        fmap[t] = v
    plane_new = [tuple(fmap[t] for t in tri) for tri in ftri]
    coord = lambda v: new_nodes[v] if v in new_nodes else nodes[v]  # noqa: E731
    gcoord, tets, ptri, fixed_ids = mesh_volumes(
        {1: fixed[1], 2: fixed[2], 3: plane_new}, coord, order, size
    )
    gmsh.finalize()

    by_xyz = {tuple(float(x) for x in coord(v)): v for v in fixed_ids}
    gmap = {}
    for t, xyz in gcoord.items():
        v = by_xyz.get(xyz)
        if v is None:
            v, next_id = next_id, next_id + 1
            new_nodes[v] = xyz
        gmap[t] = v
    # The re-meshed region must be bounded by exactly the fixed faces.
    count = collections.Counter(
        tuple(sorted(gmap[tet[j]] for j in f)) for vol in (1, 2) for tet in tets[vol]
        for f in TET_FACES
    )
    if {f for f, c in count.items() if c == 1} != set(fixed[1] + fixed[2]):
        sys.exit("Gmsh modified the fixed region boundary")

    def element(conn, edges, mid):
        conn = [gmap[v] for v in conn]
        for k, (p, q) in enumerate(edges):
            if order == 2:  # shared edges reuse the environment's mid nodes
                conn[mid + k] = env_mid.get(tuple(sorted((conn[p], conn[q]))), conn[mid + k])
        return conn

    out = []
    for vol, a in ((1, below), (2, above)):
        for tet in tets[vol]:
            out.append((11 if order == 2 else 4, [a, a], element(tet, TET_EDGES, 4)))
    features = collections.Counter()
    for tri in ptri:
        conn = element(tri, TRI_EDGES, 3)
        c = np.mean([coord(v)[:2] for v in conn[:3]], axis=0)
        a = layout.attribute_at(c)
        if a:
            out.append((9 if order == 2 else 2, [a, a], conn))
            features[a] += 1
    old_plane = {frozenset(f) for f in plane}
    kept = [
        (t, tags, nd)
        for t, tags, nd in elements
        if (t in TETRAHEDRA and tags[0] not in region)
        or (t not in TETRAHEDRA and frozenset(nd[:3]) not in old_plane)
    ]
    elements = kept + out
    used = sorted({v for _, _, nd in elements for v in nd})
    write_msh2(args.output, names, {v: coord(v) for v in used}, elements)
    print(
        "Wrote %s: region with %d tetrahedra (%d below, %d above the plane), layout "
        "triangles by attribute %s"
        % (args.output, len(tets[1]) + len(tets[2]), len(tets[1]), len(tets[2]),
           dict(sorted(features.items())))
    )


if __name__ == "__main__":
    main()
