# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED MODULE_FILE OR NOT DEFINED INVALID_CASE)
  message(FATAL_ERROR "Missing invalid metadata test arguments")
endif()
include("${MODULE_FILE}")

if(INVALID_CASE STREQUAL "no_equals")
  set(_metadata "missing")
elseif(INVALID_CASE STREQUAL "empty_record")
  set(_metadata "one=1||two=2")
elseif(INVALID_CASE STREQUAL "leading_empty_record")
  set(_metadata "|one=1")
elseif(INVALID_CASE STREQUAL "trailing_empty_record")
  set(_metadata "one=1|")
elseif(INVALID_CASE STREQUAL "empty_label")
  set(_metadata "=value")
elseif(INVALID_CASE STREQUAL "empty_value")
  set(_metadata "label=")
elseif(INVALID_CASE STREQUAL "invalid_label")
  set(_metadata "bad-label=value")
elseif(INVALID_CASE STREQUAL "duplicate")
  set(_metadata "same=first|same=second")
elseif(INVALID_CASE STREQUAL "semicolon")
  set(_metadata "label=one;two")
elseif(INVALID_CASE STREQUAL "carriage_return")
  set(_metadata "label=one\rtwo")
elseif(INVALID_CASE STREQUAL "line_feed")
  set(_metadata "label=one\ntwo")
elseif(INVALID_CASE STREQUAL "producer_pipe")
  palace_append_build_dependency(_entries "label" "one|two")
  return()
elseif(INVALID_CASE STREQUAL "producer_semicolon")
  palace_append_build_dependency(_entries "label" "one;two")
  return()
elseif(INVALID_CASE STREQUAL "producer_carriage_return")
  palace_append_build_dependency(_entries "label" "one\rtwo")
  return()
elseif(INVALID_CASE STREQUAL "producer_line_feed")
  palace_append_build_dependency(_entries "label" "one\ntwo")
  return()
elseif(INVALID_CASE STREQUAL "producer_invalid_label")
  palace_append_build_dependency(_entries "bad-label" "value")
  return()
elseif(INVALID_CASE STREQUAL "producer_empty_label")
  palace_append_build_dependency(_entries "" "value")
  return()
elseif(INVALID_CASE STREQUAL "producer_empty_value")
  palace_append_build_dependency(_entries "label" "")
  return()
elseif(INVALID_CASE STREQUAL "producer_duplicate")
  palace_append_build_dependency(_entries "same" "first")
  palace_append_build_dependency(_entries "same" "second")
  return()
else()
  message(FATAL_ERROR "Unknown invalid metadata case '${INVALID_CASE}'")
endif()

palace_format_build_dependencies("${_metadata}" _formatted _cpp_literal)
