// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

#ifndef PALACE_UTILS_ENUM_STRING_HPP
#define PALACE_UTILS_ENUM_STRING_HPP

#include <iosfwd>
#include "labels.hpp"

// Declarations for the operator<< overloads generated by PALACE_JSON_SERIALIZE_ENUM in
// configfile.cpp. Including this header is sufficient to stream-print any Palace enum that
// has a JSON serialization mapping — no need to forward-declare individual operators.

namespace palace
{

std::ostream &operator<<(std::ostream &os, const CoordinateSystem &e);
std::ostream &operator<<(std::ostream &os, const ProblemType &e);
std::ostream &operator<<(std::ostream &os, const EigenSolverBackend &e);
std::ostream &operator<<(std::ostream &os, const NonlinearEigenSolver &e);
std::ostream &operator<<(std::ostream &os, const SurfaceFlux &e);
std::ostream &operator<<(std::ostream &os, const InterfaceDielectric &e);
std::ostream &operator<<(std::ostream &os, const FrequencySampling &e);
std::ostream &operator<<(std::ostream &os, const TimeSteppingScheme &e);
std::ostream &operator<<(std::ostream &os, const Excitation &e);
std::ostream &operator<<(std::ostream &os, const LinearSolver &e);
std::ostream &operator<<(std::ostream &os, const KrylovSolver &e);
std::ostream &operator<<(std::ostream &os, const MultigridCoarsening &e);
std::ostream &operator<<(std::ostream &os, const PreconditionerSide &e);
std::ostream &operator<<(std::ostream &os, const SymbolicFactorization &e);
std::ostream &operator<<(std::ostream &os, const SparseCompression &e);
std::ostream &operator<<(std::ostream &os, const Orthogonalization &e);
std::ostream &operator<<(std::ostream &os, const DomainOrthogonalizationWeight &e);
std::ostream &operator<<(std::ostream &os, const Device &e);

}  // namespace palace

#endif  // PALACE_UTILS_ENUM_STRING_HPP
