# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#
# Configure BLAS/LAPACK libraries
#

# FindBLAS/FindLAPACK select the LP64 or ILP64 libraries from BLA_SIZEOF_INTEGER
if(NOT PALACE_WITH_64BIT_INT AND PALACE_WITH_64BIT_BLAS_INT)
  message(FATAL_ERROR "ILP64 BLAS/LAPACK interface requires PALACE_WITH_64BIT_INT")
endif()
if(PALACE_WITH_64BIT_BLAS_INT)
  set(BLA_SIZEOF_INTEGER 8)
else()
  set(BLA_SIZEOF_INTEGER 4)
endif()

# Vendor installation roots from <V>_DIR, <V>ROOT, or <V>_ROOT; without a user-provided
# BLA_VENDOR, the first one found picks the vendor
set(_BLAS_LAPACK_AUTO)
foreach(_V IN ITEMS ARMPL AOCL MKL OPENBLAS)
  set(${_V}_DIR "")
  foreach(_VAR IN ITEMS ${_V}_DIR ${_V}ROOT ${_V}_ROOT)
    if(DEFINED ENV{${_VAR}})
      set(${_V}_DIR $ENV{${_VAR}})
      break()
    endif()
  endforeach()
  if(NOT DEFINED BLA_VENDOR AND NOT _BLAS_LAPACK_AUTO AND NOT ${_V}_DIR STREQUAL "")
    set(_BLAS_LAPACK_AUTO ${_V})
  endif()
endforeach()
if(DEFINED BLA_VENDOR)
  message(STATUS "Using BLAS/LAPACK from BLA_VENDOR=${BLA_VENDOR}")
endif()

set(_BLAS_LAPACK_ROOT)
if(_BLAS_LAPACK_AUTO STREQUAL "ARMPL" OR BLA_VENDOR MATCHES "^Arm")
  if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm")
    message(WARNING "Arm PL math libraries are only intended for arm64 architecture builds")
  endif()
  if(_BLAS_LAPACK_AUTO)
    if(PALACE_WITH_OPENMP)
      set(BLA_VENDOR "Arm_mp")
    else()
      set(BLA_VENDOR "Arm")
    endif()
    message(STATUS "Using BLAS/LAPACK from Arm Performance Libraries (Arm PL)")
  endif()
  set(_BLAS_LAPACK_ROOT ${ARMPL_DIR})
elseif(_BLAS_LAPACK_AUTO STREQUAL "AOCL" OR BLA_VENDOR MATCHES "^AOCL")
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm")
    message(WARNING "AOCL math libraries are not intended for arm64 architecture builds")
  endif()
  if(_BLAS_LAPACK_AUTO)
    if(PALACE_WITH_OPENMP)
      set(BLA_VENDOR "AOCL_mt")
    else()
      set(BLA_VENDOR "AOCL")
    endif()
    message(STATUS "Using BLAS/LAPACK from AMD BLIS/libFLAME")
  endif()
  # FindBLAS/FindLAPACK search lib/LP64, but AOCL installs to lib_LP64 (and may link lib
  # to it even for ILP64 builds)
  if(PALACE_WITH_64BIT_BLAS_INT)
    set(_AOCL_LIB_DIR ${AOCL_DIR}/lib_ILP64)
  else()
    set(_AOCL_LIB_DIR ${AOCL_DIR}/lib_LP64)
  endif()
  if(NOT AOCL_DIR STREQUAL "" AND IS_DIRECTORY ${_AOCL_LIB_DIR})
    list(PREPEND CMAKE_LIBRARY_PATH ${_AOCL_LIB_DIR})
  else()
    set(_BLAS_LAPACK_ROOT ${AOCL_DIR})
  endif()
elseif(_BLAS_LAPACK_AUTO STREQUAL "MKL" OR BLA_VENDOR MATCHES "^Intel")
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm")
    message(WARNING "MKL math libraries are not intended for arm64 architecture builds")
  endif()
  if(_BLAS_LAPACK_AUTO)
    if(PALACE_WITH_OPENMP)
      set(BLA_VENDOR "Intel10_64lp")
    else()
      set(BLA_VENDOR "Intel10_64lp_seq")
    endif()
    message(STATUS "Using BLAS/LAPACK from Intel MKL")
  endif()
  set(_BLAS_LAPACK_ROOT ${MKL_DIR})
elseif(_BLAS_LAPACK_AUTO STREQUAL "OPENBLAS" OR BLA_VENDOR STREQUAL "OpenBLAS")
  if(_BLAS_LAPACK_AUTO)
    # Warning: This does NOT automatically configure for OpenMP support
    # Setting the vendor avoids a conflict with Accelerate on Darwin
    set(BLA_VENDOR "OpenBLAS")
    message(STATUS "Using BLAS/LAPACK from OpenBLAS")
  endif()
  set(_BLAS_LAPACK_ROOT ${OPENBLAS_DIR})
elseif(NOT DEFINED BLA_VENDOR)
  message(STATUS "Using BLAS/LAPACK located by CMake")
endif()

list(APPEND CMAKE_PREFIX_PATH ${_BLAS_LAPACK_ROOT})
if(_BLAS_LAPACK_AUTO STREQUAL "AOCL" AND PALACE_WITH_OPENMP)
  # Fall back to the sequential BLIS if the multithreaded one is not installed
  find_package(BLAS QUIET)
  if(NOT BLAS_FOUND)
    set(BLA_VENDOR "AOCL")
  endif()
endif()
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)

# FindLAPACK links AOCL libFLAME with -fopenmp, which is not needed
list(REMOVE_ITEM LAPACK_LIBRARIES "-fopenmp")

# Save variables to cache
set(_BLAS_LAPACK_LIBRARIES ${LAPACK_LIBRARIES} -lm ${BLAS_LIBRARIES})
list(REMOVE_DUPLICATES _BLAS_LAPACK_LIBRARIES)
list(JOIN _BLAS_LAPACK_LIBRARIES "$<SEMICOLON>" _BLAS_LAPACK_LIBRARIES)
set(BLAS_LAPACK_LIBRARIES ${_BLAS_LAPACK_LIBRARIES} CACHE STRING
  "List of library files for BLAS/LAPACK"
)
