name: Documentation Preview Cleanup
on:
  pull_request:
    types: [closed]
jobs:
  cleanup-preview-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Delete preview and history
        env:
          PRNUM: ${{ github.event.number }}
        run: |
          if [[ -d previews/PR$PRNUM ]]; then
            git config user.name "Documenter.jl"
            git config user.email "documenter@juliadocs.github.io"
            git rm -rf previews/PR$PRNUM
            git commit -m "delete preview"
            git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
            git push --force origin gh-pages-new:gh-pages
          fi
