name: Clean up GHCR images

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - palace-develop-testing
          - palace-develop
          - palace
          - palace-v0.23.1
          - palace-v1.0.2
          - palace-v1.1.0
    steps:
      - name: Delete old container versions
        uses: snok/container-retention-policy@v3
        with:
          account: awslabs
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ matrix.package }}
          cut-off: 2 weeks ago UTC
          keep-n-most-recent: 3
          tag-selection: both
