# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Emit a relocatable CTestTestfile.cmake for the [Regression] cases of an
# installed palace-unit-tests binary, so `ctest` can drive them without a build
# tree (e.g. from a Spack-installed target). Discovery reuses the binary's own
# `--list-tests --reporter xml`; the example/reference data is resolved by the
# binary at run time from PALACE_EXAMPLES_DIR / PALACE_REGRESSION_REF_DIR.
#
# Invoke in script mode:
#   cmake -D PALACE_UNIT_TESTS=<path> -D MPIEXEC=<path> -D NP=<ranks>
#         -D OUTPUT_DIR=<dir> [-D SPEC=<catch-filter>] [-D LABEL=<label>]
#         [-D EXTRA_ARGS=<;-list>]
#         -P GenerateRegressionCTest.cmake
# then: ctest --test-dir <dir> --output-on-failure

if(NOT PALACE_UNIT_TESTS OR NOT MPIEXEC OR NOT NP OR NOT OUTPUT_DIR)
  message(FATAL_ERROR "PALACE_UNIT_TESTS, MPIEXEC, NP and OUTPUT_DIR are required")
endif()
if(NOT SPEC)
  set(SPEC "[Regression]~[Long]")
endif()
if(NOT LABEL)
  set(LABEL "regression")
endif()

execute_process(
  COMMAND "${PALACE_UNIT_TESTS}" "${SPEC}" ${EXTRA_ARGS} --list-tests --reporter xml
  OUTPUT_VARIABLE xml
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Failed to list regression cases (${rc}) from ${PALACE_UNIT_TESTS}")
endif()

string(REGEX MATCHALL "<Name>[^<]*</Name>" names "${xml}")
if(NOT names)
  message(FATAL_ERROR "No regression cases matched '${SPEC}'")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(out "${OUTPUT_DIR}/CTestTestfile.cmake")
file(WRITE "${out}" "# Generated by GenerateRegressionCTest.cmake; do not edit.\n")
foreach(tag IN LISTS names)
  string(REGEX REPLACE "<Name>(.*)</Name>" "\\1" case "${tag}")
  set(cmd "\"${MPIEXEC}\" \"-np\" \"${NP}\" \"${PALACE_UNIT_TESTS}\"")
  foreach(arg IN LISTS EXTRA_ARGS)
    string(APPEND cmd " \"${arg}\"")
  endforeach()
  string(APPEND cmd " \"${case}\"")
  file(APPEND "${out}" "add_test(\"${LABEL}-${case}\" ${cmd})\n")
  file(APPEND "${out}"
       "set_tests_properties(\"${LABEL}-${case}\" PROPERTIES "
       "PROCESSORS ${NP} LABELS \"${LABEL}\" SKIP_RETURN_CODE 4)\n")
endforeach()
